"""Command handlers for the LMS Telegram bot.

Handlers are pure functions that take a message and return a response.
They don't depend on Telegram — this allows testing via --test mode.
"""

import sys
from pathlib import Path

# Add parent directory to path to import services
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from services.lms_api import get_api_client, APIError
from services.intent_router import get_router
from keyboards import get_start_keyboard

# Get the API client and router instances
api_client = get_api_client()
intent_router = get_router()


# Store keyboard for access by Telegram layer
_last_keyboard = None


def get_last_keyboard() -> dict | None:
    """Get the last keyboard that was set."""
    return _last_keyboard


def _set_keyboard(keyboard: dict | None) -> None:
    """Set the keyboard for the next response."""
    global _last_keyboard
    _last_keyboard = keyboard


async def handle_message(message: str) -> str:
    """Route a message to the appropriate handler and return a response.

    Args:
        message: The incoming message text (e.g., '/start', '/help', 'what labs are available')

    Returns:
        A text response to send back to the user.
    """
    message = message.strip()

    if message == "/start":
        return await handle_start()
    elif message == "/help":
        return await handle_help()
    elif message == "/health":
        return await handle_health()
    elif message == "/labs":
        return await handle_labs()
    elif message.startswith("/scores"):
        # Extract lab argument: /scores lab-04 -> lab-04
        parts = message.split(maxsplit=1)
        lab = parts[1] if len(parts) > 1 else ""
        return await handle_scores(lab)
    else:
        # Use LLM intent router for natural language queries
        return await handle_natural_language(message)


async def handle_start() -> str:
    """Handle /start command."""
    _set_keyboard(get_start_keyboard())
    return (
        "Welcome to the LMS Bot! 🎓\n\n"
        "I can help you explore lab data, scores, and analytics.\n\n"
        "Try asking me questions like:\n"
        "• What labs are available?\n"
        "• Show me scores for lab 4\n"
        "• Which lab has the lowest pass rate?\n"
        "• Who are the top students?\n\n"
        "Or use commands: /help, /health, /labs, /scores <lab>"
    )


async def handle_help() -> str:
    """Handle /help command."""
    _set_keyboard(get_start_keyboard())
    return (
        "Available commands:\n"
        "  /start - Welcome message\n"
        "  /help - Show this help\n"
        "  /health - Check backend status\n"
        "  /labs - List available labs\n"
        "  /scores <lab> - View pass rates for a lab\n\n"
        "Or just ask me a question in plain English!"
    )


async def handle_health() -> str:
    """Handle /health command."""
    try:
        items = await api_client.get_items()
        return f"Backend is healthy. {len(items)} items available."
    except APIError as e:
        return f"Backend error: {e.message}"


async def handle_labs() -> str:
    """Handle /labs command."""
    try:
        items = await api_client.get_items()
        # Filter for labs (type == "lab")
        labs = [item for item in items if item.type == "lab"]
        if not labs:
            return "No labs available."

        # Format lab list
        lab_lines = [f"- {lab.title}" for lab in labs]
        return "Available labs:\n" + "\n".join(lab_lines)
    except APIError as e:
        return f"Backend error: {e.message}"


async def handle_scores(lab: str) -> str:
    """Handle /scores command.

    Args:
        lab: The lab identifier (e.g., 'lab-04').

    Returns:
        Formatted pass rates for the lab.
    """
    if not lab:
        return "Usage: /scores <lab> (e.g., /scores lab-04)"

    try:
        pass_rates = await api_client.get_pass_rates(lab)
        if not pass_rates:
            return f"No pass rate data available for {lab}."

        # Format pass rates
        lines = [f"Pass rates for {lab}:"]
        for record in pass_rates:
            lines.append(
                f"- {record.task}: {record.pass_rate:.1f}% ({record.attempts} attempts)"
            )
        return "\n".join(lines)
    except APIError as e:
        return f"Backend error: {e.message}"


async def handle_natural_language(message: str) -> str:
    """Handle natural language queries using LLM intent routing.

    This function uses the LLM to decide which tool to call based on the
    user's message. There is NO regex or keyword matching here — the LLM
    receives the message and tool descriptions, then decides which tool(s)
    to call.

    Args:
        message: The user's natural language query.

    Returns:
        A text response generated by the LLM.
    """
    from keyboards import get_quick_actions_keyboard

    _set_keyboard(get_quick_actions_keyboard())

    try:
        response = await intent_router.route(message)
        return response
    except Exception as e:
        # Fallback: provide a helpful message
        return (
            f"I had trouble processing that request. "
            f"Try asking about labs, scores, or pass rates.\n\n"
            f"Technical details: {e}"
        )
